// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXWpYIOzC9Z9c7eJN5DsI5mn2ebxb0ws',
    appId: '1:531234423615:web:e337ecb0792e4a5673c98a',
    messagingSenderId: '531234423615',
    projectId: 'hospit-4a420',
    authDomain: 'hospit-4a420.firebaseapp.com',
    storageBucket: 'hospit-4a420.firebasestorage.app',
    measurementId: 'G-L28WEMQL3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5sxg6IbUc4sB_Gtsc9jDvLT9cNJhyrEg',
    appId: '1:531234423615:android:ba93e6777ccb3f8073c98a',
    messagingSenderId: '531234423615',
    projectId: 'hospit-4a420',
    storageBucket: 'hospit-4a420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Eolz9orchRDcoXKVuyjlA5H9cbUhzvg',
    appId: '1:531234423615:ios:c89a8c3efd5a94fb73c98a',
    messagingSenderId: '531234423615',
    projectId: 'hospit-4a420',
    storageBucket: 'hospit-4a420.firebasestorage.app',
    iosBundleId: 'com.example.hospit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Eolz9orchRDcoXKVuyjlA5H9cbUhzvg',
    appId: '1:531234423615:ios:c89a8c3efd5a94fb73c98a',
    messagingSenderId: '531234423615',
    projectId: 'hospit-4a420',
    storageBucket: 'hospit-4a420.firebasestorage.app',
    iosBundleId: 'com.example.hospit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiXWpYIOzC9Z9c7eJN5DsI5mn2ebxb0ws',
    appId: '1:531234423615:web:458c5af3d6736cb273c98a',
    messagingSenderId: '531234423615',
    projectId: 'hospit-4a420',
    authDomain: 'hospit-4a420.firebaseapp.com',
    storageBucket: 'hospit-4a420.firebasestorage.app',
    measurementId: 'G-04JX8B0M0Q',
  );
}
