// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP8qJcAc_mmRciZTPRffe_bRrBCK69Jgc',
    appId: '1:6504665814:web:3966939b6b656d2f34af77',
    messagingSenderId: '6504665814',
    projectId: 'hospit-cfca3',
    authDomain: 'hospit-cfca3.firebaseapp.com',
    storageBucket: 'hospit-cfca3.firebasestorage.app',
    measurementId: 'G-5QLKMB83TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJeP5FdwwYXcswSzASQe9jvKU_r0PnGc',
    appId: '1:6504665814:android:8dc1d46de088ea6934af77',
    messagingSenderId: '6504665814',
    projectId: 'hospit-cfca3',
    storageBucket: 'hospit-cfca3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTATYhvgLV7ON0s9YyImNx35DbGQl8qsg',
    appId: '1:6504665814:ios:01687928d8eafdae34af77',
    messagingSenderId: '6504665814',
    projectId: 'hospit-cfca3',
    storageBucket: 'hospit-cfca3.firebasestorage.app',
    iosBundleId: 'com.example.hospit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTATYhvgLV7ON0s9YyImNx35DbGQl8qsg',
    appId: '1:6504665814:ios:01687928d8eafdae34af77',
    messagingSenderId: '6504665814',
    projectId: 'hospit-cfca3',
    storageBucket: 'hospit-cfca3.firebasestorage.app',
    iosBundleId: 'com.example.hospit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP8qJcAc_mmRciZTPRffe_bRrBCK69Jgc',
    appId: '1:6504665814:web:e2f03ed6578003c334af77',
    messagingSenderId: '6504665814',
    projectId: 'hospit-cfca3',
    authDomain: 'hospit-cfca3.firebaseapp.com',
    storageBucket: 'hospit-cfca3.firebasestorage.app',
    measurementId: 'G-4RCL4BNNHQ',
  );
}
