// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5vaoYNz7IhD_Yl2i1Yjl0ISi3KEWOU50',
    appId: '1:174430938900:web:005df3b7f2f6d28435c401',
    messagingSenderId: '174430938900',
    projectId: 'route-1af57',
    authDomain: 'route-1af57.firebaseapp.com',
    storageBucket: 'route-1af57.firebasestorage.app',
    measurementId: 'G-RHY9PTN18H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAtD2UYmALD8bPxFbsBUlW4pqhp7kc6I',
    appId: '1:174430938900:android:aa928a74cb706fca35c401',
    messagingSenderId: '174430938900',
    projectId: 'route-1af57',
    storageBucket: 'route-1af57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwleURUJIE8kNTMHixT-pe6y17CzMXpa8',
    appId: '1:174430938900:ios:c0e088bb678c2e7135c401',
    messagingSenderId: '174430938900',
    projectId: 'route-1af57',
    storageBucket: 'route-1af57.firebasestorage.app',
    iosBundleId: 'com.example.hospit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwleURUJIE8kNTMHixT-pe6y17CzMXpa8',
    appId: '1:174430938900:ios:c0e088bb678c2e7135c401',
    messagingSenderId: '174430938900',
    projectId: 'route-1af57',
    storageBucket: 'route-1af57.firebasestorage.app',
    iosBundleId: 'com.example.hospit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5vaoYNz7IhD_Yl2i1Yjl0ISi3KEWOU50',
    appId: '1:174430938900:web:9af6f0210f140ff335c401',
    messagingSenderId: '174430938900',
    projectId: 'route-1af57',
    authDomain: 'route-1af57.firebaseapp.com',
    storageBucket: 'route-1af57.firebasestorage.app',
    measurementId: 'G-SMLDKN4PB4',
  );
}
